graphql_search_api.settings:
  type: config_object
  label: GraphQL Search API settings
  mapping:
    cache_max_age:
      type: sequence
      sequence:
        type: integer
        label: 'Cache Max-Age'
